### ISSUE TITLE
Implement members for projects

### ISSUE THREAD

**Issue by pcchin** [pcchin/study-assistant#21]
**Tasks to be completed:**
- [ ] Member's info page
- [ ] Member's edit page
- [ ] List all members
- [x] Login system
- [x] Sign up system
