### ISSUE TITLE
Implement project info & settings

### ISSUE THREAD

**Issue by pcchin** [pcchin/study-assistant#42]
**Tasks to be completed:**
- [x] Project info page
- [x] Project settings page
- [ ] Project media page
