### ISSUE TITLE
Implement optimizations

### ISSUE THREAD

**Issue by pcchin** [pcchin/study-assistant#54]
**Tasks to be completed:**
- [ ] Add async threads for accessing databases to reduce frame skips and lags (#47)
- [ ] Add custom layouts for tablets (#50)
- [ ] Add checksum verification for downloading APKs
